on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: List Installed Go Versions
      run: |
        type go
        go version
        go env
        ls -d /usr/local/*
